import { Severity } from "../../constants/severity.js";

export const drugInteractionSeedData = [
  // ── Original entries ──────────────────────────────────────────────────────
  {
    drugAName: "Ibuprofen",
    drugBName: "Aspirin",
    drugARxcui: "5640",
    drugBRxcui: "1191",
    severity: Severity.MODERATE,
    effect: "Combined use may increase the risk of gastrointestinal bleeding and may reduce aspirin's antiplatelet effect when taken at the same time.",
    recommendation: "Avoid routine combined use unless advised by a clinician. If both are needed, ask a clinician or pharmacist about timing and bleeding risk.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Warfarin",
    drugBName: "Aspirin",
    drugARxcui: "11289",
    drugBRxcui: "1191",
    severity: Severity.HIGH,
    effect: "Combined use significantly increases bleeding risk through both antiplatelet and anticoagulant mechanisms.",
    recommendation: "Use together only under direct medical supervision with close monitoring for bleeding and anticoagulation status.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Metformin",
    drugBName: "Alcohol",
    drugARxcui: "6809",
    drugBRxcui: "448",
    severity: Severity.MODERATE,
    effect: "Alcohol may increase the risk of metformin-associated lactic acidosis and can impair blood glucose control.",
    recommendation: "Limit alcohol intake and seek clinician guidance, especially with heavy drinking, liver disease, kidney disease, or acute illness.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Lisinopril",
    drugBName: "Potassium Chloride",
    drugARxcui: "29046",
    drugBRxcui: "8591",
    severity: Severity.HIGH,
    effect: "Combined use may raise potassium levels and substantially increase the risk of hyperkalemia, which can cause serious cardiac arrhythmias.",
    recommendation: "Use together only with clinician guidance and regular potassium monitoring.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Simvastatin",
    drugBName: "Clarithromycin",
    drugARxcui: "36567",
    drugBRxcui: "21212",
    severity: Severity.HIGH,
    effect: "Clarithromycin inhibits CYP3A4 and can increase simvastatin exposure several-fold, significantly raising the risk of muscle toxicity including rhabdomyolysis.",
    recommendation: "Avoid combining. A clinician may pause simvastatin during clarithromycin therapy or select an alternative antibiotic.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Amoxicillin",
    drugBName: "Methotrexate",
    drugARxcui: "723",
    drugBRxcui: "6851",
    severity: Severity.MODERATE,
    effect: "Amoxicillin may reduce methotrexate renal clearance, increasing methotrexate blood levels and the risk of toxicity including bone marrow suppression.",
    recommendation: "Use with clinician guidance. Monitor for signs of methotrexate toxicity such as mouth sores, unusual bruising, or abnormal blood counts.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Ciprofloxacin",
    drugBName: "Tizanidine",
    drugARxcui: "2551",
    drugBRxcui: "57258",
    severity: Severity.HIGH,
    effect: "Ciprofloxacin strongly inhibits CYP1A2 and can greatly increase tizanidine exposure, causing severe hypotension, sedation, and psychomotor impairment.",
    recommendation: "This combination is contraindicated. Contact a clinician for an alternative antibiotic or muscle relaxant.",
    source: "Local verified seed data",
  },

  // ── Warfarin interactions ─────────────────────────────────────────────────
  {
    drugAName: "Warfarin",
    drugBName: "Paracetamol",
    drugARxcui: "11289",
    drugBRxcui: "161",
    severity: Severity.MODERATE,
    effect: "Regular or high-dose paracetamol use can potentiate warfarin's anticoagulant effect and increase INR, raising the risk of bleeding.",
    recommendation: "Keep paracetamol within recommended doses. Increase INR monitoring frequency when starting or stopping regular paracetamol use.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Warfarin",
    drugBName: "Ibuprofen",
    drugARxcui: "11289",
    drugBRxcui: "5640",
    severity: Severity.HIGH,
    effect: "Ibuprofen inhibits platelet aggregation and can increase gastrointestinal bleeding risk. It also inhibits CYP2C9 and may increase warfarin blood levels.",
    recommendation: "Avoid this combination. Use paracetamol (at recommended doses with INR monitoring) as an alternative analgesic.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Warfarin",
    drugBName: "Metronidazole",
    drugARxcui: "11289",
    drugBRxcui: "6922",
    severity: Severity.HIGH,
    effect: "Metronidazole inhibits CYP2C9 and CYP3A4, significantly reducing warfarin metabolism and increasing INR — raising serious bleeding risk.",
    recommendation: "Avoid if possible. If combined, reduce warfarin dose and monitor INR closely during and for 1–2 weeks after metronidazole therapy.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Warfarin",
    drugBName: "Ciprofloxacin",
    drugARxcui: "11289",
    drugBRxcui: "2551",
    severity: Severity.MODERATE,
    effect: "Ciprofloxacin may inhibit warfarin metabolism via CYP1A2, increasing anticoagulant effect and bleeding risk.",
    recommendation: "Monitor INR closely during and after ciprofloxacin therapy. Adjust warfarin dose as guided by INR results.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Warfarin",
    drugBName: "Clarithromycin",
    drugARxcui: "11289",
    drugBRxcui: "21212",
    severity: Severity.HIGH,
    effect: "Clarithromycin inhibits CYP3A4 and CYP2C9, increasing warfarin exposure and raising serious bleeding risk.",
    recommendation: "Monitor INR closely during clarithromycin therapy and for at least one week after stopping. Consider a warfarin dose reduction.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Warfarin",
    drugBName: "Sertraline",
    drugARxcui: "11289",
    drugBRxcui: "36437",
    severity: Severity.MODERATE,
    effect: "SSRIs impair platelet aggregation and, combined with warfarin, can increase the risk of bleeding, particularly gastrointestinal bleeding.",
    recommendation: "Monitor INR when starting or stopping sertraline. Report any unusual bruising or bleeding to a clinician.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Warfarin",
    drugBName: "Carbamazepine",
    drugARxcui: "11289",
    drugBRxcui: "2002",
    severity: Severity.MODERATE,
    effect: "Carbamazepine strongly induces CYP enzymes and increases warfarin metabolism, which can significantly reduce anticoagulant effect.",
    recommendation: "Monitor INR closely when starting or stopping carbamazepine. Warfarin dose increases are often required.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Warfarin",
    drugBName: "Fluconazole",
    drugARxcui: "11289",
    drugBRxcui: "4450",
    severity: Severity.HIGH,
    effect: "Fluconazole strongly inhibits CYP2C9, dramatically increasing warfarin blood levels and raising serious bleeding risk.",
    recommendation: "Avoid combining if possible. If necessary, reduce warfarin dose by up to 50% and monitor INR very closely.",
    source: "Local verified seed data",
  },

  // ── NSAID interactions ────────────────────────────────────────────────────
  {
    drugAName: "Ibuprofen",
    drugBName: "Lisinopril",
    drugARxcui: "5640",
    drugBRxcui: "29046",
    severity: Severity.MODERATE,
    effect: "NSAIDs can reduce the antihypertensive effect of ACE inhibitors and increase the risk of acute kidney injury, particularly in volume-depleted patients.",
    recommendation: "Avoid routine combined use. If both are needed, monitor blood pressure and kidney function closely and keep ibuprofen use to the minimum effective dose for the shortest duration.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Ibuprofen",
    drugBName: "Methotrexate",
    drugARxcui: "5640",
    drugBRxcui: "6851",
    severity: Severity.HIGH,
    effect: "NSAIDs reduce methotrexate renal clearance, increasing methotrexate blood levels and the risk of serious toxicity including bone marrow suppression and mucositis.",
    recommendation: "Avoid this combination. Use paracetamol as the preferred analgesic in patients taking methotrexate, and discuss with a clinician.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Aspirin",
    drugBName: "Methotrexate",
    drugARxcui: "1191",
    drugBRxcui: "6851",
    severity: Severity.MODERATE,
    effect: "Aspirin may reduce methotrexate renal clearance, increasing the risk of methotrexate toxicity including myelosuppression.",
    recommendation: "Avoid combining aspirin with rheumatological doses of methotrexate. Consult a clinician for analgesic alternatives.",
    source: "Local verified seed data",
  },

  // ── Statin interactions ───────────────────────────────────────────────────
  {
    drugAName: "Simvastatin",
    drugBName: "Amlodipine",
    drugARxcui: "36567",
    drugBRxcui: "17767",
    severity: Severity.MODERATE,
    effect: "Amlodipine inhibits CYP3A4 and can increase simvastatin exposure by up to 1.5 times, raising the risk of muscle toxicity (myopathy).",
    recommendation: "Limit simvastatin dose to 20 mg/day when combined with amlodipine. Report any unexplained muscle pain, weakness, or dark urine immediately.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Simvastatin",
    drugBName: "Amiodarone",
    drugARxcui: "36567",
    drugBRxcui: "1728",
    severity: Severity.HIGH,
    effect: "Amiodarone inhibits CYP3A4 and significantly increases simvastatin exposure, substantially raising the risk of rhabdomyolysis and acute kidney injury.",
    recommendation: "Do not exceed simvastatin 20 mg/day with amiodarone. A clinician may prefer switching to rosuvastatin or pravastatin, which are not CYP3A4-metabolized.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Atorvastatin",
    drugBName: "Clarithromycin",
    drugARxcui: "83367",
    drugBRxcui: "21212",
    severity: Severity.HIGH,
    effect: "Clarithromycin inhibits CYP3A4 and can significantly increase atorvastatin exposure, raising the risk of myopathy and rhabdomyolysis.",
    recommendation: "Consider pausing atorvastatin during clarithromycin therapy. Discuss alternative antibiotics with a clinician.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Simvastatin",
    drugBName: "Diltiazem",
    drugARxcui: "36567",
    drugBRxcui: "3443",
    severity: Severity.MODERATE,
    effect: "Diltiazem inhibits CYP3A4 and can increase simvastatin exposure, raising the risk of muscle toxicity.",
    recommendation: "Limit simvastatin dose to 10 mg/day when combined with diltiazem. Switch to a non-CYP3A4 statin if higher doses are needed.",
    source: "Local verified seed data",
  },

  // ── Beta-blocker / CCB interactions ──────────────────────────────────────
  {
    drugAName: "Metoprolol",
    drugBName: "Verapamil",
    drugARxcui: "40049",
    drugBRxcui: "11170",
    severity: Severity.HIGH,
    effect: "Combined use of a beta-blocker and a non-dihydropyridine calcium channel blocker can cause severe bradycardia, AV block, hypotension, or heart failure.",
    recommendation: "Avoid this combination unless under close cardiology supervision with continuous monitoring. Contact a clinician before combining.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Metoprolol",
    drugBName: "Diltiazem",
    drugARxcui: "40049",
    drugBRxcui: "3443",
    severity: Severity.MODERATE,
    effect: "Additive negative chronotropic and inotropic effects may cause bradycardia, hypotension, or heart block when combined.",
    recommendation: "Use with caution. Monitor heart rate and blood pressure regularly. Contact a clinician if heart rate drops below 60 bpm.",
    source: "Local verified seed data",
  },

  // ── Cardiac interactions ──────────────────────────────────────────────────
  {
    drugAName: "Digoxin",
    drugBName: "Amiodarone",
    drugARxcui: "3407",
    drugBRxcui: "1728",
    severity: Severity.HIGH,
    effect: "Amiodarone inhibits P-glycoprotein and reduces digoxin renal clearance, increasing digoxin blood levels and the risk of digoxin toxicity.",
    recommendation: "Reduce digoxin dose by 30–50% when starting amiodarone. Monitor digoxin serum levels closely and watch for toxicity signs such as nausea, visual disturbances, and new arrhythmias.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Sildenafil",
    drugBName: "Nitroglycerin",
    drugARxcui: "21041",
    drugBRxcui: "9313",
    severity: Severity.HIGH,
    effect: "Combined use causes severe, potentially life-threatening hypotension through additive vasodilation. This is among the most dangerous drug combinations in pharmacology.",
    recommendation: "This combination is absolutely contraindicated. Do not use any nitrate within 24 hours of sildenafil. Seek emergency care if accidental combination occurs.",
    source: "Local verified seed data",
  },

  // ── Iron interactions ─────────────────────────────────────────────────────
  {
    drugAName: "Ferrous Sulfate",
    drugBName: "Ciprofloxacin",
    drugARxcui: "4582",
    drugBRxcui: "2551",
    severity: Severity.MODERATE,
    effect: "Oral iron forms insoluble complexes with fluoroquinolones in the GI tract, reducing ciprofloxacin absorption by up to 70% and potentially rendering the antibiotic ineffective.",
    recommendation: "Take ciprofloxacin at least 2 hours before or 4–6 hours after iron supplements to avoid this interaction.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Ferrous Sulfate",
    drugBName: "Doxycycline",
    drugARxcui: "4582",
    drugBRxcui: "3640",
    severity: Severity.MODERATE,
    effect: "Iron chelates doxycycline in the GI tract and can reduce doxycycline absorption by up to 80%, significantly reducing its antibiotic effectiveness.",
    recommendation: "Take doxycycline at least 2–3 hours before or 4 hours after iron supplements.",
    source: "Local verified seed data",
  },
  {
    drugAName: "Ferrous Sulfate",
    drugBName: "Levothyroxine",
    drugARxcui: "4582",
    drugBRxcui: "10582",
    severity: Severity.MODERATE,
    effect: "Iron supplements can significantly reduce levothyroxine absorption from the GI tract, potentially leading to under-treatment of hypothyroidism.",
    recommendation: "Take levothyroxine on an empty stomach at least 4 hours before or after iron supplements. Monitor thyroid function if combined use is unavoidable.",
    source: "Local verified seed data",
  },

  // ── PPI interactions ──────────────────────────────────────────────────────
  {
    drugAName: "Omeprazole",
    drugBName: "Clopidogrel",
    drugARxcui: "40790",
    drugBRxcui: "174742",
    severity: Severity.MODERATE,
    effect: "Omeprazole inhibits CYP2C19 and reduces the conversion of clopidogrel to its active antiplatelet metabolite, potentially increasing cardiovascular event risk.",
    recommendation: "Consider using pantoprazole (a weaker CYP2C19 inhibitor) instead. Discuss the choice of PPI with a cardiologist for patients on dual antiplatelet therapy.",
    source: "Local verified seed data",
  },

  // ── Serotonin syndrome risk ───────────────────────────────────────────────
  {
    drugAName: "Fluoxetine",
    drugBName: "Tramadol",
    drugARxcui: "4493",
    drugBRxcui: "10689",
    severity: Severity.HIGH,
    effect: "Combined use of an SSRI and tramadol significantly increases the risk of serotonin syndrome, characterized by agitation, tremor, hyperthermia, and tachycardia. Tramadol also inhibits serotonin reuptake and may lower the seizure threshold when combined with SSRIs.",
    recommendation: "Avoid this combination. If pain management is needed in patients on SSRIs, discuss alternative analgesics such as paracetamol or low-dose NSAIDs with a clinician.",
    source: "Local verified seed data",
  },

  // ── ACE inhibitor interactions ────────────────────────────────────────────
  {
    drugAName: "Lisinopril",
    drugBName: "Spironolactone",
    drugARxcui: "29046",
    drugBRxcui: "9997",
    severity: Severity.MODERATE,
    effect: "Combined use of an ACE inhibitor and a potassium-sparing diuretic significantly increases the risk of hyperkalemia, particularly in patients with chronic kidney disease or diabetes.",
    recommendation: "Monitor potassium levels regularly. Avoid potassium supplements unless directed by a clinician. In high-risk patients, regular electrolyte checks are essential.",
    source: "Local verified seed data",
  },
];
