export const medicationSeedData = [
  // ── Analgesics / NSAIDs ──────────────────────────────────────────────────
  { rxcui: "5640",   genericName: "Ibuprofen",           aliases: ["Advil", "Motrin", "Nurofen", "Brufen", "Caldolor", "Midol"] },
  { rxcui: "161",    genericName: "Paracetamol",          aliases: ["Acetaminophen", "Tylenol", "Panadol", "Calpol", "Tempra", "Datril", "Feverall"] },
  { rxcui: "1191",   genericName: "Aspirin",              aliases: ["Bayer", "Ecotrin", "Bufferin", "Anacin", "Empirin", "Loprin"] },
  { rxcui: "7258",   genericName: "Naproxen",             aliases: ["Aleve", "Naprosyn", "Anaprox", "Naprelan", "Flanax"] },
  { rxcui: "3355",   genericName: "Diclofenac",           aliases: ["Voltaren", "Cataflam", "Cambia", "Zipsor", "Dyloject"] },
  { rxcui: "35827",  genericName: "Ketorolac",            aliases: ["Toradol", "Acular", "Sprix"] },
  { rxcui: "140587", genericName: "Celecoxib",            aliases: ["Celebrex", "Onsenal"] },
  { rxcui: "5781",   genericName: "Indomethacin",         aliases: ["Indocin", "Indocid", "Tivorbex"] },
  { rxcui: "8522",   genericName: "Piroxicam",            aliases: ["Feldene", "Flogobene"] },
  { rxcui: "6741",   genericName: "Mefenamic Acid",       aliases: ["Ponstel", "Ponstan", "Meftal"] },
  { rxcui: "7646",   genericName: "Meloxicam",            aliases: ["Mobic", "Vivlodex", "Qmiiz"] },

  // ── Opioids ──────────────────────────────────────────────────────────────
  { rxcui: "7052",   genericName: "Morphine",             aliases: ["MS Contin", "Oramorph", "Kadian", "Roxanol", "Avinza"] },
  { rxcui: "2670",   genericName: "Codeine",              aliases: ["Codeine Phosphate", "Tylenol with Codeine", "Robitussin AC"] },
  { rxcui: "7804",   genericName: "Oxycodone",            aliases: ["OxyContin", "Percocet", "Percodan", "Roxicodone", "Xtampza"] },
  { rxcui: "10689",  genericName: "Tramadol",             aliases: ["Ultram", "ConZip", "Rybix", "Ryzolt"] },
  { rxcui: "4337",   genericName: "Fentanyl",             aliases: ["Duragesic", "Actiq", "Sublimaze", "Abstral", "Lazanda"] },
  { rxcui: "5489",   genericName: "Hydrocodone",          aliases: ["Vicodin", "Norco", "Lortab", "Zohydro", "Hysingla"] },
  { rxcui: "1819",   genericName: "Buprenorphine",        aliases: ["Suboxone", "Subutex", "Belbuca", "Butrans", "Brixia"] },
  { rxcui: "7243",   genericName: "Naloxone",             aliases: ["Narcan", "Evzio", "Kloxxado"] },
  { rxcui: "3423",   genericName: "Hydromorphone",        aliases: ["Dilaudid", "Exalgo", "Palladone"] },
  { rxcui: "7238",   genericName: "Naltrexone",           aliases: ["Vivitrol", "ReVia", "Depade"] },

  // ── Antibiotics ───────────────────────────────────────────────────────────
  { rxcui: "723",    genericName: "Amoxicillin",          aliases: ["Amoxil", "Trimox", "Moxatag", "Larotid"] },
  { rxcui: "733",    genericName: "Ampicillin",           aliases: ["Principen", "Totacillin", "Omnipen"] },
  { rxcui: "7980",   genericName: "Phenoxymethylpenicillin", aliases: ["Penicillin V", "Pen VK", "Veetids", "Cilicaine"] },
  { rxcui: "2231",   genericName: "Cephalexin",           aliases: ["Keflex", "Keftab", "Panixine"] },
  { rxcui: "2194",   genericName: "Cefuroxime",           aliases: ["Ceftin", "Zinacef", "Kefurox"] },
  { rxcui: "2193",   genericName: "Ceftriaxone",          aliases: ["Rocephin"] },
  { rxcui: "20489",  genericName: "Cefixime",             aliases: ["Suprax", "Cefixoral", "Oroken"] },
  { rxcui: "2551",   genericName: "Ciprofloxacin",        aliases: ["Cipro", "Ciprobay", "Ciproxin", "Proquin"] },
  { rxcui: "41493",  genericName: "Levofloxacin",         aliases: ["Levaquin", "Quixin", "Iquix"] },
  { rxcui: "18631",  genericName: "Azithromycin",         aliases: ["Zithromax", "Z-Pack", "Zmax", "Azasite"] },
  { rxcui: "21212",  genericName: "Clarithromycin",       aliases: ["Biaxin", "Klacid", "Clarihexal"] },
  { rxcui: "4053",   genericName: "Erythromycin",         aliases: ["Ery-Tab", "Erythrocin", "Ilosone", "PCE"] },
  { rxcui: "3640",   genericName: "Doxycycline",          aliases: ["Vibramycin", "Doryx", "Oracea", "Adoxa", "Atridox"] },
  { rxcui: "10364",  genericName: "Tetracycline",         aliases: ["Sumycin", "Actisite", "Ala-Tet", "Panmycin"] },
  { rxcui: "6922",   genericName: "Metronidazole",        aliases: ["Flagyl", "MetroGel", "Noritate", "Vandazole"] },
  { rxcui: "2582",   genericName: "Clindamycin",          aliases: ["Cleocin", "Dalacin", "ClindaMax", "Evoclin"] },
  { rxcui: "10829",  genericName: "Trimethoprim-Sulfamethoxazole", aliases: ["Bactrim", "Septra", "Cotrimoxazole", "TMP-SMX", "Co-trimoxazole"] },
  { rxcui: "7454",   genericName: "Nitrofurantoin",       aliases: ["Macrobid", "Macrodantin", "Furadantin"] },
  { rxcui: "4450",   genericName: "Fluconazole",          aliases: ["Diflucan", "Trican", "Canesten Oral"] },
  { rxcui: "28237",  genericName: "Itraconazole",         aliases: ["Sporanox", "Tolsura", "Onmel"] },
  { rxcui: "6103",   genericName: "Ketoconazole",         aliases: ["Nizoral", "Extina", "Xolegel"] },
  { rxcui: "21241",  genericName: "Voriconazole",         aliases: ["Vfend", "Voriconazole Pfizer"] },
  { rxcui: "703",    genericName: "Vancomycin",           aliases: ["Vancocin", "Firvanq", "Vancomycin HCl"] },

  // ── Cardiovascular ────────────────────────────────────────────────────────
  { rxcui: "11289",  genericName: "Warfarin",             aliases: ["Coumadin", "Jantoven", "Marevan"] },
  { rxcui: "5224",   genericName: "Heparin",              aliases: ["Hep-Lock", "Monoject", "Heparin Sodium"] },
  { rxcui: "67108",  genericName: "Enoxaparin",           aliases: ["Lovenox", "Clexane", "Inhixa"] },
  { rxcui: "1114195", genericName: "Rivaroxaban",         aliases: ["Xarelto"] },
  { rxcui: "1364430", genericName: "Apixaban",            aliases: ["Eliquis"] },
  { rxcui: "1037045", genericName: "Dabigatran",          aliases: ["Pradaxa", "Pradax"] },
  { rxcui: "174742", genericName: "Clopidogrel",          aliases: ["Plavix", "Iscover", "Grepid"] },
  { rxcui: "83367",  genericName: "Atorvastatin",         aliases: ["Lipitor", "Torvast", "Atorlip"] },
  { rxcui: "36567",  genericName: "Simvastatin",          aliases: ["Zocor", "FloLipid", "Simcor"] },
  { rxcui: "301542", genericName: "Rosuvastatin",         aliases: ["Crestor", "Ezallor", "Rosulip"] },
  { rxcui: "42463",  genericName: "Pravastatin",          aliases: ["Pravachol", "Lipostat", "Selectin"] },
  { rxcui: "41126",  genericName: "Fluvastatin",          aliases: ["Lescol", "Vastin"] },
  { rxcui: "29046",  genericName: "Lisinopril",           aliases: ["Zestril", "Prinivil", "Qbrelis", "Carace"] },
  { rxcui: "3827",   genericName: "Enalapril",            aliases: ["Vasotec", "Renitec", "Epaned", "Lexxel"] },
  { rxcui: "35208",  genericName: "Ramipril",             aliases: ["Altace", "Tritace", "Ramace", "Ramipres"] },
  { rxcui: "1998",   genericName: "Captopril",            aliases: ["Capoten", "Acepril", "Lopirin"] },
  { rxcui: "54552",  genericName: "Perindopril",          aliases: ["Coversyl", "Aceon", "Prestalia"] },
  { rxcui: "203160", genericName: "Losartan",             aliases: ["Cozaar", "Losartan Potassium"] },
  { rxcui: "69749",  genericName: "Valsartan",            aliases: ["Diovan", "Prexxartan"] },
  { rxcui: "83515",  genericName: "Irbesartan",           aliases: ["Avapro", "Aprovel", "Irbesartan Teva"] },
  { rxcui: "321064", genericName: "Olmesartan",           aliases: ["Benicar", "Olmetec", "Votum"] },
  { rxcui: "73494",  genericName: "Telmisartan",          aliases: ["Micardis", "Kinzalmono", "Pritor"] },
  { rxcui: "17767",  genericName: "Amlodipine",           aliases: ["Norvasc", "Istin", "Amlodis", "Amlocor"] },
  { rxcui: "7417",   genericName: "Nifedipine",           aliases: ["Procardia", "Adalat", "Nifediac", "Afeditab"] },
  { rxcui: "3443",   genericName: "Diltiazem",            aliases: ["Cardizem", "Tiazac", "Cartia XT", "Dilacor"] },
  { rxcui: "11170",  genericName: "Verapamil",            aliases: ["Calan", "Isoptin", "Verelan", "Covera-HS"] },
  { rxcui: "40049",  genericName: "Metoprolol",           aliases: ["Lopressor", "Toprol-XL", "Selokeen", "Betaloc"] },
  { rxcui: "1202",   genericName: "Atenolol",             aliases: ["Tenormin", "Tenoretic"] },
  { rxcui: "19484",  genericName: "Bisoprolol",           aliases: ["Zebeta", "Concor", "Cardicor", "Emcor"] },
  { rxcui: "20352",  genericName: "Carvedilol",           aliases: ["Coreg", "Eucardic", "Dilatrend"] },
  { rxcui: "8787",   genericName: "Propranolol",          aliases: ["Inderal", "Innopran XL", "Hemangeol"] },
  { rxcui: "6142",   genericName: "Labetalol",            aliases: ["Normodyne", "Trandate", "Presdate"] },
  { rxcui: "9947",   genericName: "Sotalol",              aliases: ["Betapace", "Sorine", "Sotylize"] },
  { rxcui: "4603",   genericName: "Furosemide",           aliases: ["Lasix", "Frusemide", "Frusenex"] },
  { rxcui: "5487",   genericName: "Hydrochlorothiazide",  aliases: ["Microzide", "HydroDIURIL", "HCTZ", "Oretic"] },
  { rxcui: "9997",   genericName: "Spironolactone",       aliases: ["Aldactone", "CaroSpir", "Berlactone"] },
  { rxcui: "52769",  genericName: "Eplerenone",           aliases: ["Inspra"] },
  { rxcui: "3407",   genericName: "Digoxin",              aliases: ["Lanoxin", "Digitek", "Digox"] },
  { rxcui: "1728",   genericName: "Amiodarone",           aliases: ["Cordarone", "Pacerone", "Nexterone"] },
  { rxcui: "9313",   genericName: "Nitroglycerin",        aliases: ["Nitrostat", "Nitrolingual", "NitroMist", "Nitro-Dur"] },
  { rxcui: "33978",  genericName: "Isosorbide Mononitrate", aliases: ["Imdur", "Monoket", "ISMO"] },
  { rxcui: "5876",   genericName: "Isosorbide Dinitrate", aliases: ["Isordil", "Dilatrate-SR", "BiDil"] },

  // ── Antidiabetics ─────────────────────────────────────────────────────────
  { rxcui: "6809",   genericName: "Metformin",            aliases: ["Glucophage", "Fortamet", "Glumetza", "Riomet", "Glycomet"] },
  { rxcui: "4815",   genericName: "Glipizide",            aliases: ["Glucotrol", "Minidiab", "Glibenese"] },
  { rxcui: "4821",   genericName: "Glyburide",            aliases: ["DiaBeta", "Micronase", "Glibenclamide", "Daonil", "Euglucon"] },
  { rxcui: "25789",  genericName: "Glimepiride",          aliases: ["Amaryl", "Glimy", "Glimpid"] },
  { rxcui: "33738",  genericName: "Pioglitazone",         aliases: ["Actos", "Glustin", "Competact"] },
  { rxcui: "593411", genericName: "Sitagliptin",          aliases: ["Januvia", "Xelevia", "Tesavel"] },
  { rxcui: "857974", genericName: "Saxagliptin",          aliases: ["Onglyza", "Kombiglyze"] },
  { rxcui: "1545653", genericName: "Empagliflozin",       aliases: ["Jardiance", "Synjardy"] },
  { rxcui: "1373458", genericName: "Canagliflozin",       aliases: ["Invokana", "Vokanamet"] },
  { rxcui: "1488565", genericName: "Dapagliflozin",       aliases: ["Farxiga", "Forxiga", "Xigduo"] },
  { rxcui: "475968", genericName: "Liraglutide",          aliases: ["Victoza", "Saxenda", "Xultophy"] },
  { rxcui: "274783", genericName: "Insulin Glargine",     aliases: ["Lantus", "Toujeo", "Basaglar", "Semglee"] },
  { rxcui: "274770", genericName: "Insulin Aspart",       aliases: ["NovoLog", "NovoRapid", "Fiasp"] },
  { rxcui: "86009",  genericName: "Insulin Lispro",       aliases: ["Humalog", "Admelog", "Lyumjev"] },
  { rxcui: "5856",   genericName: "Insulin",              aliases: ["Humulin", "Novolin", "ReliOn"] },
  { rxcui: "319840", genericName: "Exenatide",            aliases: ["Byetta", "Bydureon"] },
  { rxcui: "2200644", genericName: "Semaglutide",         aliases: ["Ozempic", "Rybelsus", "Wegovy"] },

  // ── CNS / Psychiatric ─────────────────────────────────────────────────────
  { rxcui: "36437",  genericName: "Sertraline",           aliases: ["Zoloft", "Lustral", "Serlift"] },
  { rxcui: "4493",   genericName: "Fluoxetine",           aliases: ["Prozac", "Sarafem", "Selfemra", "Rapiflux"] },
  { rxcui: "32937",  genericName: "Paroxetine",           aliases: ["Paxil", "Seroxat", "Brisdelle", "Pexeva"] },
  { rxcui: "321988", genericName: "Escitalopram",         aliases: ["Lexapro", "Cipralex", "Esitalo"] },
  { rxcui: "2556",   genericName: "Citalopram",           aliases: ["Celexa", "Cipramil", "Cipram"] },
  { rxcui: "39786",  genericName: "Venlafaxine",          aliases: ["Effexor", "Effexor XR", "Vensir", "Dobupal"] },
  { rxcui: "72625",  genericName: "Duloxetine",           aliases: ["Cymbalta", "Irenka", "Yentreve"] },
  { rxcui: "42347",  genericName: "Bupropion",            aliases: ["Wellbutrin", "Zyban", "Aplenzin", "Forfivo", "Contrave"] },
  { rxcui: "15996",  genericName: "Mirtazapine",          aliases: ["Remeron", "Avanza", "Zispin"] },
  { rxcui: "717",    genericName: "Amitriptyline",        aliases: ["Elavil", "Endep", "Tryptanol", "Laroxyl"] },
  { rxcui: "596",    genericName: "Alprazolam",           aliases: ["Xanax", "Niravam", "Xanax XR"] },
  { rxcui: "3322",   genericName: "Diazepam",             aliases: ["Valium", "Diastat", "Valtoco", "Stesolid"] },
  { rxcui: "2598",   genericName: "Clonazepam",           aliases: ["Klonopin", "Rivotril", "Paxam"] },
  { rxcui: "6470",   genericName: "Lorazepam",            aliases: ["Ativan", "Loraz", "Tavor"] },
  { rxcui: "2764",   genericName: "Oxazepam",             aliases: ["Serax", "Serenid", "Alepam"] },
  { rxcui: "39993",  genericName: "Zolpidem",             aliases: ["Ambien", "Intermezzo", "Edluar", "Stilnoct"] },
  { rxcui: "39998",  genericName: "Zaleplon",             aliases: ["Sonata", "Starnoc", "Andante"] },
  { rxcui: "202433", genericName: "Quetiapine",           aliases: ["Seroquel", "Seroquel XR", "Biquelle"] },
  { rxcui: "35636",  genericName: "Risperidone",          aliases: ["Risperdal", "Risperidal Consta", "Perseris"] },
  { rxcui: "61381",  genericName: "Olanzapine",           aliases: ["Zyprexa", "Zyprexa Zydis", "Zalasta"] },
  { rxcui: "89013",  genericName: "Aripiprazole",         aliases: ["Abilify", "Aristada", "Abilify Maintena"] },
  { rxcui: "6448",   genericName: "Lithium",              aliases: ["Eskalith", "Lithobid", "Lithonate", "Priadel"] },
  { rxcui: "25480",  genericName: "Gabapentin",           aliases: ["Neurontin", "Gralise", "Horizant"] },
  { rxcui: "187832", genericName: "Pregabalin",           aliases: ["Lyrica", "Lyrica CR"] },
  { rxcui: "38404",  genericName: "Topiramate",           aliases: ["Topamax", "Trokendi XR", "Qudexy XR"] },
  { rxcui: "28439",  genericName: "Lamotrigine",          aliases: ["Lamictal", "Lamictal XR", "Lamictal CD"] },
  { rxcui: "2002",   genericName: "Carbamazepine",        aliases: ["Tegretol", "Carbatrol", "Epitol", "Equetro"] },
  { rxcui: "11118",  genericName: "Valproic Acid",        aliases: ["Depakote", "Depakene", "Stavzor", "Epilim", "Valparin"] },
  { rxcui: "8275",   genericName: "Phenytoin",            aliases: ["Dilantin", "Phenytek", "Epanutin", "Solfoton"] },
  { rxcui: "114477", genericName: "Levetiracetam",        aliases: ["Keppra", "Keppra XR", "Elepsia"] },
  { rxcui: "135447", genericName: "Donepezil",            aliases: ["Aricept", "Aricept ODT"] },
  { rxcui: "115854", genericName: "Memantine",            aliases: ["Namenda", "Namenda XR", "Ebixa", "Axura"] },
  { rxcui: "2403",   genericName: "Chlorpromazine",       aliases: ["Thorazine", "Largactil", "Chloractil"] },
  { rxcui: "5205",   genericName: "Haloperidol",          aliases: ["Haldol", "Serenace", "Haldol Decanoate"] },

  // ── GI ────────────────────────────────────────────────────────────────────
  { rxcui: "40790",  genericName: "Omeprazole",           aliases: ["Prilosec", "Losec", "Zegerid", "Omesec"] },
  { rxcui: "283742", genericName: "Esomeprazole",         aliases: ["Nexium", "Nexium 24HR", "Vimovo"] },
  { rxcui: "40790",  genericName: "Pantoprazole",         aliases: ["Protonix", "Pantoloc", "Somac"] },
  { rxcui: "203056", genericName: "Lansoprazole",         aliases: ["Prevacid", "Zoton", "Ogastro"] },
  { rxcui: "9143",   genericName: "Ranitidine",           aliases: ["Zantac", "Tritec", "Ranixal"] },
  { rxcui: "4278",   genericName: "Famotidine",           aliases: ["Pepcid", "Pepcid AC", "Pepcid Complete"] },
  { rxcui: "6913",   genericName: "Metoclopramide",       aliases: ["Reglan", "Metozolv ODT", "Maxolon"] },
  { rxcui: "26225",  genericName: "Ondansetron",          aliases: ["Zofran", "Zuplenz", "Emetron"] },
  { rxcui: "6459",   genericName: "Loperamide",           aliases: ["Imodium", "Diamode", "Imodium A-D"] },
  { rxcui: "1901",   genericName: "Bisacodyl",            aliases: ["Dulcolax", "Correctol", "Carter's Pills"] },
  { rxcui: "3630",   genericName: "Domperidone",          aliases: ["Motilium", "Motinorm", "Costi"] },
  { rxcui: "40798",  genericName: "Lactulose",            aliases: ["Cephulac", "Kristalose", "Constulose"] },

  // ── Respiratory / Allergy ─────────────────────────────────────────────────
  { rxcui: "435",    genericName: "Albuterol",            aliases: ["Salbutamol", "Ventolin", "ProAir", "Proventil", "AccuNeb"] },
  { rxcui: "203165", genericName: "Montelukast",          aliases: ["Singulair"] },
  { rxcui: "20610",  genericName: "Cetirizine",           aliases: ["Zyrtec", "Reactine", "Allerid", "Histazine"] },
  { rxcui: "47613",  genericName: "Loratadine",           aliases: ["Claritin", "Alavert", "Tavist ND", "Claratyne"] },
  { rxcui: "203164", genericName: "Fexofenadine",         aliases: ["Allegra", "Telfast", "Fastofen"] },
  { rxcui: "3498",   genericName: "Diphenhydramine",      aliases: ["Benadryl", "Sominex", "Nytol", "ZzzQuil"] },
  { rxcui: "19831",  genericName: "Budesonide",           aliases: ["Pulmicort", "Rhinocort", "Symbicort", "Entocort"] },
  { rxcui: "41126",  genericName: "Fluticasone",          aliases: ["Flonase", "Flovent", "Flixonase", "Veramyst"] },
  { rxcui: "274179", genericName: "Salmeterol",           aliases: ["Serevent", "Advair"] },
  { rxcui: "10689",  genericName: "Ipratropium",          aliases: ["Atrovent", "Ipravent"] },
  { rxcui: "42316",  genericName: "Tiotropium",           aliases: ["Spiriva", "Spiriva Respimat"] },

  // ── Hormones / Thyroid ───────────────────────────────────────────────────
  { rxcui: "10582",  genericName: "Levothyroxine",        aliases: ["Synthroid", "Levoxyl", "Unithroid", "Eltroxin", "Euthyrox"] },
  { rxcui: "6847",   genericName: "Methimazole",          aliases: ["Tapazole", "Thyrozol", "Thiamazole"] },
  { rxcui: "8820",   genericName: "Propylthiouracil",     aliases: ["PTU", "Propyl-Thyracil"] },
  { rxcui: "6751",   genericName: "Medroxyprogesterone",  aliases: ["Depo-Provera", "Provera", "Cycrin"] },
  { rxcui: "4083",   genericName: "Estradiol",            aliases: ["Estrace", "Vivelle-Dot", "Climara", "Alora"] },
  { rxcui: "8727",   genericName: "Progesterone",         aliases: ["Prometrium", "Crinone", "Endometrin"] },
  { rxcui: "10109",  genericName: "Testosterone",         aliases: ["AndroGel", "Testim", "Axiron", "Depo-Testosterone"] },
  { rxcui: "2585",   genericName: "Clomifene",            aliases: ["Clomid", "Serophene", "Milophene"] },

  // ── Corticosteroids ───────────────────────────────────────────────────────
  { rxcui: "8638",   genericName: "Prednisone",           aliases: ["Deltasone", "Rayos", "Orasone", "Prednicot"] },
  { rxcui: "3264",   genericName: "Dexamethasone",        aliases: ["Decadron", "Ozurdex", "Dexpak", "Maxidex"] },
  { rxcui: "6902",   genericName: "Methylprednisolone",   aliases: ["Medrol", "Depo-Medrol", "Solu-Medrol", "A-Methapred"] },
  { rxcui: "5492",   genericName: "Hydrocortisone",       aliases: ["Cortef", "Solu-Cortef", "Hydrocortone", "Cortizone"] },

  // ── Rheumatology / Immunology ────────────────────────────────────────────
  { rxcui: "6851",   genericName: "Methotrexate",         aliases: ["Rheumatrex", "Trexall", "Otrexup", "RasuVo", "Methoject"] },
  { rxcui: "5521",   genericName: "Hydroxychloroquine",   aliases: ["Plaquenil", "Quineprox"] },
  { rxcui: "1489",   genericName: "Azathioprine",         aliases: ["Imuran", "Azasan"] },
  { rxcui: "3008",   genericName: "Cyclosporine",         aliases: ["Sandimmune", "Neoral", "Restasis", "Gengraf"] },
  { rxcui: "9974",   genericName: "Tacrolimus",           aliases: ["Prograf", "Astagraf XL", "Envarsus", "Protopic"] },
  { rxcui: "37451",  genericName: "Mycophenolate",        aliases: ["CellCept", "Myfortic", "MMF"] },
  { rxcui: "9966",   genericName: "Sulfasalazine",        aliases: ["Azulfidine", "Salazopyrin"] },

  // ── Antivirals ────────────────────────────────────────────────────────────
  { rxcui: "321",    genericName: "Acyclovir",            aliases: ["Zovirax", "Sitavig"] },
  { rxcui: "88452",  genericName: "Valacyclovir",         aliases: ["Valtrex", "Zelitrex"] },
  { rxcui: "284817", genericName: "Oseltamivir",          aliases: ["Tamiflu"] },
  { rxcui: "1109997", genericName: "Sofosbuvir",          aliases: ["Sovaldi", "Harvoni", "Epclusa"] },

  // ── Gout ─────────────────────────────────────────────────────────────────
  { rxcui: "519",    genericName: "Allopurinol",          aliases: ["Zyloprim", "Lopurin", "Aloprim"] },
  { rxcui: "2683",   genericName: "Colchicine",           aliases: ["Colcrys", "Mitigare", "Gloperba"] },
  { rxcui: "41493",  genericName: "Febuxostat",           aliases: ["Uloric", "Adenuric"] },

  // ── Urology ───────────────────────────────────────────────────────────────
  { rxcui: "77492",  genericName: "Tamsulosin",           aliases: ["Flomax", "Urimax", "Secotex"] },
  { rxcui: "59831",  genericName: "Finasteride",          aliases: ["Proscar", "Propecia", "Finpecia"] },
  { rxcui: "275427", genericName: "Dutasteride",          aliases: ["Avodart", "Jalyn"] },
  { rxcui: "21041",  genericName: "Sildenafil",           aliases: ["Viagra", "Revatio"] },
  { rxcui: "187899", genericName: "Tadalafil",            aliases: ["Cialis", "Adcirca", "Alyq"] },

  // ── Anticoagulation support ───────────────────────────────────────────────
  { rxcui: "8591",   genericName: "Potassium Chloride",   aliases: ["Potassium Supplement", "Klor-Con", "K-Dur", "K-Tab", "Micro-K"] },
  { rxcui: "448",    genericName: "Alcohol",              aliases: ["Ethanol", "Beer", "Wine", "Spirits"] },

  // ── Supplements / Vitamins ────────────────────────────────────────────────
  { rxcui: "4582",   genericName: "Ferrous Sulfate",      aliases: ["Iron Supplement", "Slow Fe", "Fer-In-Sol", "Fergon"] },
  { rxcui: "4614",   genericName: "Folic Acid",           aliases: ["Folate", "Vitamin B9", "FA", "Folcres"] },
  { rxcui: "11072",  genericName: "Vitamin D",            aliases: ["Cholecalciferol", "Ergocalciferol", "Calciferol", "D3"] },
  { rxcui: "1821",   genericName: "Calcium Carbonate",    aliases: ["Tums", "Caltrate", "Os-Cal", "Cali-Cal"] },
  { rxcui: "6572",   genericName: "Magnesium Oxide",      aliases: ["Mag-Ox", "Uro-Mag", "Maox", "Magnesium Supplement"] },
  { rxcui: "9878",   genericName: "Vitamin B12",          aliases: ["Cyanocobalamin", "Methylcobalamin", "Nascobal"] },
  { rxcui: "3521",   genericName: "Vitamin C",            aliases: ["Ascorbic Acid", "Cecon", "Vita-C"] },

  // ── CNS adjuncts ──────────────────────────────────────────────────────────
  { rxcui: "2599",   genericName: "Clonidine",            aliases: ["Catapres", "Kapvay", "Nexiclon XR", "Duraclon"] },
  { rxcui: "8629",   genericName: "Prazosin",             aliases: ["Minipress", "Vasoflex"] },
  { rxcui: "47476",  genericName: "Doxazosin",            aliases: ["Cardura", "Cardura XL"] },
  { rxcui: "3638",   genericName: "Doxepin",              aliases: ["Sinequan", "Adapin", "Silenor", "Xepin"] },
  { rxcui: "6913",   genericName: "Promethazine",         aliases: ["Phenergan", "Promethegan", "Antinaus"] },

  // ── Oncology (selected key drugs) ────────────────────────────────────────
  { rxcui: "1946",   genericName: "Cyclophosphamide",     aliases: ["Cytoxan", "Neosar"] },
  { rxcui: "5911",   genericName: "Tamoxifen",            aliases: ["Nolvadex", "Soltamox"] },
  { rxcui: "10592",  genericName: "Letrozole",            aliases: ["Femara"] },
  { rxcui: "200284", genericName: "Anastrozole",          aliases: ["Arimidex"] },

  // ── Miscellaneous ─────────────────────────────────────────────────────────
  { rxcui: "6913",   genericName: "Chloroquine",          aliases: ["Aralen", "Chlorquin"] },
  { rxcui: "44818",  genericName: "Ritonavir",            aliases: ["Norvir", "Kaletra"] },
  { rxcui: "190530", genericName: "Zolmitriptan",         aliases: ["Zomig", "Zomig ZMT"] },
  { rxcui: "41493",  genericName: "Sumatriptan",          aliases: ["Imitrex", "Alsuma", "Sumavel", "Onzetra"] },
  { rxcui: "121191", genericName: "Modafinil",            aliases: ["Provigil", "Alertec"] },
  { rxcui: "41493",  genericName: "Methylphenidate",      aliases: ["Ritalin", "Concerta", "Metadate", "Quillivant"] },
  { rxcui: "3498",   genericName: "Amphetamine",          aliases: ["Adderall", "Dextroamphetamine", "Vyvanse"] },
  { rxcui: "9143",   genericName: "Baclofen",             aliases: ["Lioresal", "Ozobax", "Fleqsuvy"] },
  { rxcui: "36117",  genericName: "Tizanidine",           aliases: ["Zanaflex", "Sirdalud"] },
  { rxcui: "7980",   genericName: "Cyclobenzaprine",      aliases: ["Flexeril", "Amrix", "Fexmid"] },
  { rxcui: "41167",  genericName: "Dextromethorphan",     aliases: ["Robitussin DM", "NyQuil", "DM Cough"] },
  { rxcui: "6572",   genericName: "Pseudoephedrine",      aliases: ["Sudafed", "Sudafed PE", "Contac"] },
  { rxcui: "39913",  genericName: "Alendronate",          aliases: ["Fosamax", "Binosto"] },
  { rxcui: "72610",  genericName: "Risedronate",          aliases: ["Actonel", "Atelvia"] },
  { rxcui: "6141",   genericName: "Latanoprost",          aliases: ["Xalatan", "Xelpros"] },
  { rxcui: "68968",  genericName: "Timolol",              aliases: ["Timoptic", "Betimol", "Istalol"] },
];
